//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by d:\Mis documentos\Privado\Programación\proyectos\TorrenTres\res\Torment.rc
//
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDI_TORMENT                     128
#define IDR_MAINMENU                    129
#define ID_FILE_OPENTORRENT             130
#define ID_FILE_EXIT                    131
#define ID_TOOLS_SETTINGS               132
#define IDR_CONTEXTMENU                 133
#define ID_TORRENT_SHOWINFO             134
#define ID_TORRENT_CANCELDOWNLOAD       135
#define ID_TORRENT_GETNEWCLIENTLIST     136
#define IDR_TORRENTMENU                 138
#define ID_VIEW_TORRENTINFO             139
#define IDR_TORRENTMENU1                139
#define ID_VIEW_BLOCKMAP                140
#define ID_VIEW_CLIENTLIST              141
#define IDB_PROGRESSBAR_O               142
#define IDB_PROGRESSBAR_B               143
#define IDB_PROGRESSBAR_G               144
#define IDB_PROGRESSBAR_R               145
#define ID_FILE_CANCELDOWNLOAD          146
#define ID_FILE_GETNEWCLIENTLIST        147
#define ID_FILE_HIDEWINDOW              148
#define IDI_TORRENT                     150
#define IDD_CONNECTIONSETTINGS_DIALOG   150
#define IDD_FILESETTINGS_DIALOG         151
#define IDD_WINDOWSETTINGS_DIALOG       152
#define IDR_LOGO                        153
#define IDD_DIALOG1                     154
#define IDD_ABOUT_DIALOG                154
#define ID_HELP_ABOUTTORMENT            155
#define IDI_ICON1                       156
#define IDI_TRAY                        156
#define IDD_PRIORITY_DIALOG             157
#define IDB_BITMAP1                     158
#define IDB_PROGRESSBAR_Y               158
#define IDD_DIALOG2                     159
#define IDI_BALL_B                      160
#define IDD_ABOUT_DIALOG1               160
#define IDI_BALL_G                      161
#define IDI_BALL_O                      162
#define IDI_BALL_R                      163
#define IDI_BALL_Y                      164
#define IDI_PAUSE                       165
#define IDC_TORRENTLIST                 1000
#define IDC_CHECK1                      1001
#define IDC_UNLIMITEDUPLOADRATE_CHECK   1001
#define IDC_CREATESUBDIRS_CHECK         1001
#define IDC_EDIT1                       1002
#define IDC_MAXUPLOADRATE_EDIT          1002
#define IDC_AUTOLOAD_EDIT               1002
#define IDC_SPIN1                       1003
#define IDC_MAXUPLOADRATE_SPIN          1003
#define IDC_MAXUPLOADS_EDIT             1004
#define IDC_SPIN2                       1005
#define IDC_MAXUPLOADS_SPIN             1005
#define IDC_CHECK2                      1006
#define IDC_AUTOLOAD_CHECK              1006
#define IDC_STATUSMINIMIZETOSYSTRAY_CHECK 1006
#define IDC_EDIT2                       1007
#define IDC_HISTORY_EDIT                1007
#define IDC_CHECK3                      1008
#define IDC_HISTORY_CHECK               1008
#define IDC_BUTTON1                     1009
#define IDC_MOVEUP_BUTTON               1009
#define IDC_AUTOLOAD_BUTTON             1009
#define IDC_ADD                         1009
#define IDC_CHECK4                      1010
#define IDC_CHECK5                      1011
#define IDC_CHECK6                      1012
#define IDC_EDIT3                       1013
#define IDC_PORT_EDIT                   1013
#define IDC_SPIN3                       1014
#define IDC_PORT_SPIN                   1014
#define IDC_MAXCONNECTIONS_EDIT         1015
#define IDC_MAXCONNECTIONS_SPIN         1016
#define IDC_UNLIMITEDCONNECTIONS_CHECK  1017
#define IDC_RADIO1                      1018
#define IDC_DOWNLOADALGORITHM_RAREST_RADIO 1018
#define IDC_FORCEIP_CHECK               1018
#define IDC_RADIO2                      1019
#define IDC_DOWNLOADALGORITHM_RANDOM_RADIO 1019
#define IDC_FORCEIP_EDIT                1019
#define IDC_RADIO3                      1020
#define IDC_DOWNLOADALGORITHM_SEQUENTIAL_RADIO 1020
#define IDC_ASKTOSAVE_CHECK             1021
#define IDC_REMOVEUNDERSCORES_CHECK     1022
#define IDC_DEFAULTSAVEDIR_CHECK        1023
#define IDC_DEFAULTSAVE_EDIT            1024
#define IDC_DEFAULTSAVE_BUTTON          1025
#define IDC_MINIMIZETOSYSTRAY_CHECK     1026
#define IDC_STATUSONLOAD_CHECK          1027
#define IDC_PRIORITY_LIST               1028
#define IDC_BUTTON2                     1029
#define IDC_MOVEDOWN_BUTTON             1029
#define IDC_HISTORY_BUTTON              1029
#define IDC_REMOVE                      1029
#define IDC_DOUBLEBLOCKMAP_CHECK        1030
#define IDC_CHECK7                      1031
#define IDC_CHECK8                      1032
#define IDC_DONTCACHE_CHECK             1033
#define IDC_ENABLE_CHECK                1037
#define IDC_FILELIST                    1038
#define IDC_PRIORITYLIST                1039
#define IDC_MEMUSAGE                    1041
#define IDC_ALLOCATIONMETHOD_FULL       1045
#define IDC_ALLOCATIONMETHOD_ONDEMAND   1046
#define IDC_ALLOCATIONMETHOD_SPARSE     1047
#define ID_TORRENT_SETFILEPRIORITIES    32772
#define ID_FILE_SETFILEPRIORITIES       32773
#define ID_CLIENT_DISCONNECT            32774
#define ID_CLIENT_CHOKE                 32775
#define ID_CLIENT_UNCHOKE               32776
#define ID_TORRENT_MODIFYFILEPRIORITIES 32778
#define ID_FILE_PAUSE                   32779
#define ID_TORRENT_PAUSE                32780
#define ID_TORRENT_RESUME               32781
#define ID_VIEW_LOGWINDOW               32782
#define ID_Menu                         32783
#define ID_Menu32784                    32784
#define ID_VIEW_BANDWIDTHMONITOR        32785
#define ID_VIEW_SELECTCOLUMNS           32786

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        167
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         1046
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
